{% set name = "pypdb" %}
{% set version = "2.3" %}
{% set sha256 = "a14aa2b5e5ece60552178fe3d35bdb0b38d6b0e9e7216bcc9c174386904c249f" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - pandas

test:
  imports:
    - pypdb

about:
  home: http://www.wgilpin.com/pypdb_docs/html/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python toolkit for performing searches with the RCSB Protein Data Bank (PDB) using its XML-based API.
  dev_url: https://github.com/williamgilpin/pypdb

extra:
  recipe-maintainers:
    - tsenapathi
    - moorepants
