{% set name = "pypdb" %}
{% set version = "2.4" %}
{% set sha256 = "2e865f9cb41c789d78988a73e12d2e329a50d65f28da26d2011202073fde7365" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - pypdb

about:
  home: http://www.wgilpin.com/pypdb_docs/html/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python toolkit for performing searches with the RCSB Protein Data Bank (PDB) using its XML-based API.
  dev_url: https://github.com/williamgilpin/pypdb

extra:
  recipe-maintainers:
    - tsenapathi
    - moorepants
