{% set name = "pypdb" %}
{% set version = "2.5" %}
{% set sha256 = "8be4575a5b8adafaa2e62a268249cd2b30d87480117d3165487f1b011c24d445" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.0
    - pip >=26.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pypdb

about:
  home: http://www.wgilpin.com/pypdb_docs/html/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python toolkit for performing searches with the RCSB Protein Data Bank (PDB) using its XML-based API.
  dev_url: https://github.com/williamgilpin/pypdb

extra:
  recipe-maintainers:
    - tsenapathi
    - moorepants
