travis:
  secure:
    BINSTAR_TOKEN: NS//xjjWNue4ZFtwhf+Eq8S5fHUN+WrXp2RDENW5b0jZ48ONBm+5CMHEchQWtFuG/6CtIqwOObFa6OnQJxqVAcUoGw7FdsniMg9GRDvEtk+FAVaF6Rgm8b8JH48tQOYlkf/EoaXXVPl5+154mt3Lj8BLzyO8MfrDofjdeHGp4PQ3AbrELpsHAsKXa43IVSL1XfRvPee785Q1lfHELWp1j0FgSUGUMKRRLRpwWrPfcpI14vt+vlg36y8MF9vz94gbi2FqOKZg2+CoHryEd5d5ydcsnR3gWmIC8pggUFO3s5KmHazTJ5jGgQZz71y8bII7fVHNGdlSKLBldqlbNUnCYaw+//jDgNGxbt11qslkLX644uMcDipAKJFNV5iuXfUhbS4CUxi235TY0QC7fweT1dnS5oCnEYyWlunncEe9B2+eSjwtCL6Y6YDFx7pdLV2ofela9ABefssny8jbhjluBnezJUloZxuJ+aBl6/ViKy/p37v0vidk3YAnrsbhT/l00n5JDfwYemrODon+GtBNP8dlIAe9G1sguXP8mf33yrDqngPkFfWRrp0CglKk4NwHgtKZmhgL4bT/YJaSLpMO13TeznvqiR8qiZNGr0p26oDrlnLiLpBFjBxAK6RuO6E49gD0wq8YMkEFZFy3lugEuefs/c76Xn8OPjtHM3ISfoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
